---
title: "20236 Time Series Analysis - Assignment 5"
author:
- Simone Arrigoni (1794692)
- Luca Badolato (3086040)
- Simone Valle (3088281)
subtitle: "Bocconi University"
date: April 15, 2020
output: pdf_document
header-includes:
  \usepackage[utf8]{inputenc}
  \usepackage{setspace}
  \usepackage{algpseudocode}
  \usepackage{algorithm}
  \usepackage{bm}
  \usepackage{amsmath}
  \usepackage{amssymb}
  \usepackage{graphicx}
  \usepackage{subfig}
  \usepackage{booktabs, caption}
  \usepackage{array}
  \usepackage{threeparttable}
  \usepackage{listings}
  \usepackage{physics}
  \usepackage{float}
  \floatplacement{figure}{H}
  \usepackage{color} %red, green, blue, yellow, cyan, magenta, black, white
  \definecolor{mygreen}{RGB}{28,172,0} % color values Red, Green, Blue
  \definecolor{mylilas}{RGB}{170,55,241}
  \DeclareMathOperator*{\E}{\mathbb{E}}
  \DeclareMathOperator*{\Ec}{\mathbb{E}_t}
---

```{r, include=FALSE}

# Load useful packages
library(utf8)
library(labeling)
library(rmarkdown)
library(httr)
library(knitr)
library(tseries)
library(tinytex)
library(scales)
library(magrittr)
library(stringr)
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(ggpubr)
library(ggthemes)
library(latex2exp)
library(kableExtra)
library(reshape2)
library(depmixS4)
library(dlm)

# Settings
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE,
                      echo    = FALSE,
                      include = TRUE,
                      fig.pos = "H",
                      fig.align = "center")
```

\section{Exercise}

In this exercise we consider the \textbf{Nile} data, available in R. This provides the measurements of the annual flow of the river Nile at Ashwan, for the period 1871-1970.

We first plot the data in Figure \ref{fig:Nile_plot}.

```{r, fig.width=6, fig.height=2.5, fig.cap="\\label{fig:Nile_plot}Annual flow of the river Nile (Ashwan)"}

# Dataframe creation
Nile_df <- Nile

# Time series plot

```

The data appears non-stationary, presenting an evident change point.
